Jamuro.AdventureWorks.SimpleDemo/Jamuro.AdventureWorks.SimpleDemo/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jamuro.AdventureWorks.SimpleDemo.ViewModels;
using Jamuro.AdventureWorks.Services.Workers;

namespace Jamuro.AdventureWorks.SimpleDemo.Controllers
{
    public class HelpController : BaseController
    {
        public ActionResult EntityFramework()
        {
            EntityFrameworkViewModel entityFrameworkViewModel = new EntityFrameworkViewModel();
            return View(entityFrameworkViewModel);
        }

        public ActionResult Linq()
        {
            LinqViewModel linqViewModel = new LinqViewModel();
            return View(linqViewModel);
        }

        public ActionResult SQLMonitorization()
        {
            return View();
        }

        public ActionResult SQLIndexes()
        {
            return View();
        }

        public ActionResult SQLResourceOptimization()
        {
            return View();
        }

        public ActionResult SQLQueryOptimization()
        {
            return View();
        }

        
    }
}

Jamuro.AdventureWorks.SimpleDemo/Jamuro.AdventureWorks.SimpleDemo/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jamuro.AdventureWorks.SimpleDemo.ViewModels;
using Jamuro.AdventureWorks.Services.Workers;
using Jamuro.AdventureWorks.Services.Workers.Interfaces;

namespace Jamuro.AdventureWorks.SimpleDemo.Controllers
{
    public class ProductController : BaseController
    {
        public readonly IProductWorker m_productWorker;

        public ProductController(IProductWorker productWorker):base()
        {
            m_productWorker = productWorker;
        }


        public ActionResult GetAllBikes()
        {
            var model = m_productWorker.GetAllBikes();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikes", viewModel);
        }

        public ActionResult GetAllBikesWithIncludes()
        {
            var model = m_productWorker.GetAllBikesWithIncludes();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikesWithIncludes", viewModel);
        }

        public ActionResult GetAllBikesWithIncludesNoTracking()
        {
            var model = m_productWorker.GetAllBikesWithIncludesNoTracking();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikesWithIncludesNoTracking", viewModel);
        }

        public ActionResult GetAllBikesWithCheckAllAny()
        {
            var model = m_productWorker.GetAllBikesWithCheckAllAny();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikesWithCheckAllAny", viewModel);
        }

        public ActionResult GetAllBikesWithCheckAllCount()
        {
            var model = m_productWorker.GetAllBikesWithCheckAllCount();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikesWithCheckAllCount", viewModel);
        }

        public ActionResult GetAllBikesWithCheckOne()
        {
            var model = m_productWorker.GetAllBikesWithCheckOne();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikesWithCheckOne", viewModel);
        }

        public ActionResult GetAllBikesWithCheckExists()
        {
            var model = m_productWorker.GetAllBikesWithCheckExists();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikesWithCheckExists", viewModel);
        }

        public ActionResult GetMostExpensiveBikes(int maxNumber=25, bool topInjectedInSQL=true)
        {
            var model = m_productWorker.GetMostExpensiveBikes(maxNumber, topInjectedInSQL);
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            ViewBag.MaxNumber = maxNumber;
            ViewBag.TopInjectedInSQL = topInjectedInSQL;
            return View("MostExpensiveBikes", viewModel);
        }

        public ActionResult GetAllBikesWithAllImprovements()
        {
            var model = m_productWorker.GetAllBikesWithAllImprovements();
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.Products = model;
            return View("AllBikesWithAllImprovements", viewModel);
        }
    }
}

Jamuro.AdventureWorks.SimpleDemo/Jamuro.AdventureWorks.SimpleDemo/Views/Shared/_Layout.cshtml
@using Jamuro.AdventureWorks.Resources
@using Jamuro.AdventureWorks.SimpleDemo.ViewModels
@using Jamuro.AdventureWorks.SimpleDemo.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Labels.ApplicationName @(ViewBag.Title != null ? "- " + ViewBag.Title : "") </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/shared")
</head>
<body>
    @{ 
        var waitingWindowViewModel = WaitingWindowViewModel.GetDefaultValues();
    }
    @Html.Partial("_Waiting", waitingWindowViewModel)

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("dotNetters " + Labels.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Labels.Home, "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            @Labels.Bikes
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetAllBikes", "Product")">
                                    @Labels.AllBikes - @Labels.N1Problem
                                    <span class="text-danger"><strong>@Labels.Bad</strong></span>
                                </a>
                            </li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetAllBikesWithIncludes", "Product")">
                                    @Labels.AllBikes - @Labels.AddIncludes
                                    <span class="text-success">@Labels.Good</span>
                                </a>
                            </li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetAllBikesWithIncludesNoTracking", "Product")">
                                    @Labels.AllBikes - @Labels.AddIncludes + @Labels.NoTracking
                                    <span class="text-success"><strong>@Labels.Good</strong></span>
                                </a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                            <a class="waiting-menu-item" href="@Url.Action("GetAllBikesWithCheckAllCount", "Product")">
                                @Labels.AllBikesWithCheckAllCountTitle
                                <span class="text-danger"><strong>@Labels.Bad</strong></span>
                            </a>
                            </li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetAllBikesWithCheckAllAny", "Product")">
                                    @Labels.AllBikesWithCheckAllAnyTitle
                                    <span class="text-danger"><strong>@Labels.Bad</strong></span>
                                </a>
                            </li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetAllBikesWithCheckOne", "Product")">
                                    @Labels.AllBikesWithCheckAnyTitle
                                    <span class="text-success">@Labels.Good</span>
                                </a>
                            </li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetAllBikesWithCheckExists", "Product")">
                                    @Labels.AllBikesWithCheckWIthExistsTitle
                                    <span class="text-success"><strong>@Labels.Good</strong></span>
                                </a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetMostExpensiveBikes", "Product", new { maxNumber = 10, topInjectedInSQL = false })">
                                    @Labels.Top10MostExpensiveBikes
                                    <span class="text-danger"><strong>@Labels.Bad</strong></span>
                                </a>
                            </li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetMostExpensiveBikes", "Product", new { maxNumber = 10, topInjectedInSQL = true })">
                                    @Labels.Top10MostExpensiveBikes
                                    <span class="text-success"><strong>@Labels.Good</strong></span>
                                </a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a class="waiting-menu-item" href="@Url.Action("GetAllBikesWithAllImprovements", "Product")">
                                    @Labels.AllBikes - @Labels.AddIncludes + @Labels.NoTracking + @Labels.RestrictSQLFields
                                    <span class="text-success"><strong>@Labels.Best</strong></span>
                                </a>
                            </li>
                            
                </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            @Labels.Help
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink(Labels.SQLMonitorization, "SQLMonitorization", "Help")</li>                          
                            <li>@Html.ActionLink(Labels.SQLResourceOptimization, "SQLResourceOptimization", "Help")</li>
                            <li>@Html.ActionLink(Labels.SQLQueryOptimization, "SQLQueryOptimization", "Help")</li>
                            <li>@Html.ActionLink(Labels.SQLIndexes, "SQLIndexes", "Help")</li>
                            
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("LINQ", "LINQ", "Help")</li>
                            <li>@Html.ActionLink("Entity Framework", "EntityFramework", "Help")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderSection("ElapsedTime", false)
        @RenderBody()        
        <hr />
        <footer>           
            <p>&copy; @DateTime.Now.Year - @Labels.ApplicationName | <a href="@Labels.JamuroBlog" target="_blank">José A. Muro</a> | <a href="mailto:jmuro@deloitte.es">jmuro@deloitte.es</a> | <a href="mailto:jmuro77@hotmail.com">jmuro77@hotmail.com</a></p>
        </footer>
        <ul class="langs" style="list-style:none;">
            <li style="display:inline;">
                <a href="" class="set-lang" data-lang="es-es"><img src="@Url.GetImage("Spain.png", false)" /></a>
            </li>
            <li style="display:inline;">
                <a href="" class="set-lang" data-lang="en-US"><img src="@Url.GetImage("United-States-of-America.png", false)" /></a>
            </li>
        </ul>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
    $(document).ready(function(){
        @*$("#@waitingWindowViewModel.Name").fadeOut(500);*@

        $("a.waiting-menu-item").click(function(e) {
            $("#@waitingWindowViewModel.Name").show();
            return true;
        })

        $(".toogle-sqlquerystress-result").click(function () {
            $(".sqlquerystress-result").toggle();
        })

        $(".toogle-sqlprofiler-details").click(function () {
            $(".toogle-sqlprofiler-content").toggle();
        })

        $(".toogle-sqlextendedevents-details").click(function () {
            $(".toogle-sqlextendedevents-content").toggle();
        })

        $(".toogle-details").click(function () {
            $(".toogle-details-content").toggle();
        })

        var lang = JamuroAdventuresWorksSimpleDemo.Cookies.getCookie("@MemoryCacheManager.GetAppSettings("jamuro:MultiLanguageCookieName")");
        $(".set-lang[data-lang='" + lang + "'] img").addClass("active-lang");

        $(".set-lang").on("click", function (event) {
            var lang = $(this).attr("data-lang");
            JamuroAdventuresWorksSimpleDemo.Cookies.setCookie("@MemoryCacheManager.GetAppSettings("jamuro:MultiLanguageCookieName")", lang, 30);
            location.reload(true);
        })
    });


    </script>

</body>
</html>

Jamuro.AdventureWorks.SimpleDemo/Jamuro.AdventureWorks.SimpleDemo/Views/Shared/_N1Problem.cshtml
<hr/>
<h3>What is Select N+1 Problem?</h3>
<p>
    <b>ORMs</b> can help you to address the impedance mismatch between relational databases and object oriented models and by that <b>make your life simpler</b>. 
    But not knowing about some of their pitfalls can decrease your performance dramatically. 
    One of those pitfalls is the select N+1 problem. 
    This problem is being caused mainly because most of the <b>ORMs out there are enabling lazy loading behavior by default</b>. 
    When we have a parent-children relation the problem can raise its ugly head. 
    The problem is happening when we are executing a single query and then N following queries (N is the number of parent entities) in order to query for something. 
    As you can expect <b>doing N+1 queries instead of a single one will flood your database with queries that we can and should avoid</b>. 
    This is very unacceptable.
</p>
<p>
    More Information:
    <a href="http://blogs.microsoft.co.il/gilf/2010/08/18/select-n1-problem-how-to-decrease-your-orm-performance/" target="_blank">
        Select N+1 Problem – How to Decrease Your ORM Performance
    </a>
</p>

Jamuro.AdventureWorks.SimpleDemo/Jamuro.AdventureWorks.SimpleDemo/Views/Shared/_Waiting.cshtml
@using Jamuro.AdventureWorks.Resources
@using Jamuro.AdventureWorks.SimpleDemo.ViewModels

@model WaitingWindowViewModel

<div id="@Model.Name" class="modal">
    <!-- Modal content -->
    <div class="modal-content-preloader text-center">
        <p style="font-size:1.6em">@Model.Message...</p>
        <img style="width:50%" src="/content/images/Preloader.1.gif" alt="@Labels.Waiting"/>
    </div>
</div>